/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smei.gui.espacios;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import smei.dao.DAOEspacio;
import smei.modelos.Espacio;
import smei.modelos.Usuario;
import smei.util.GUIUtil;
import smei.util.Mail;

/**
 *
 * @author Ernesto Mancebo T
 */
public class VisualizadorDeEspacios extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizadorDeEspacios
     */
    private static VisualizadorDeEspacios instancia = new VisualizadorDeEspacios();
    private final String[] columnHeaders = {"", "Nombre", "Cant. Personas", "Descripcion", "Habilitado"};
    private final Class[] columnsTypes = {java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class};
    private DAOEspacio daoEspacio = new DAOEspacio();
    private ArrayList<Espacio> modeloEspacio;
    private Usuario usuario;

    private VisualizadorDeEspacios() {
        initComponents();
        initializeValues();
    }

    public static VisualizadorDeEspacios getInstance() {
        return instancia;
    }

    public void initializeValues() {

        tblVisualizarEspacios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblVisualizarEspacios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable target = (JTable) e.getSource();
                    if (target.getSelectedColumn() != 0) {
                        MaestroEspacios activeFrame = MaestroEspacios.getInstance();

                        activeFrame.limpiarData();

                        activeFrame.cargarDataFromID(daoEspacio.getEspacioByID(modeloEspacio.get(target.getSelectedRow()).getId()));
                        GUIUtil.addFrameToDesktopPanel(getInstance().getDesktopPane(), activeFrame);
                        GUIUtil.deshabilitarEdicion(activeFrame);
                        GUIUtil.habilitarBtnModificar(activeFrame);
                        GUIUtil.habilitarBtnSalir(activeFrame);
                    }
                }
            }
        });

        //Add table Model
        cargarTabla();
    }

    private void cargarTabla() {
        GUIUtil.setMultiPuporseModelToTable(tblVisualizarEspacios,
                daoEspacio.crearTablaEspacio(modeloEspacio = daoEspacio.getAllEspacios()), columnHeaders, columnsTypes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarEspacios = new javax.swing.JTable();
        txtBuscarEspacio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarEspacios = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        chkDeshabilitar = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(726, 374));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVisualizarEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisualizarEspacios.setToolTipText("");
        jScrollPane1.setViewportView(tblVisualizarEspacios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 690, 238));
        getContentPane().add(txtBuscarEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 11, 189, -1));

        jLabel1.setText("Buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        btnEliminarEspacios.setText("Deshabilitar Espacio");
        btnEliminarEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEspaciosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 298, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 298, -1, -1));

        chkDeshabilitar.setSelected(true);
        chkDeshabilitar.setText("Deshabilitar");
        chkDeshabilitar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDeshabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(chkDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 298, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEspaciosActionPerformed
        ArrayList<Integer> values = new ArrayList<Integer>();

        for (Integer i : GUIUtil.getIndexOfSelectedRows(tblVisualizarEspacios, 0)) {
            values.add(modeloEspacio.get(i).getId());

            Mail.getInstance().sendAMail(Mail.TipoEmail.ACTUALIZAR_ESPACIO, usuario,
                    modeloEspacio.get(i).getDescripcion(), daoEspacio.getCorreosInvolucradosEnReservaDeEspacio(modeloEspacio.get(i)));
        }

        if (!values.isEmpty()) {
            if (chkDeshabilitar.isSelected()) {
                daoEspacio.deshabilitarEspacios(values);
            } else {
                daoEspacio.habilitarEspacios(values);
            }
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Favor seleccione al menos un espacio para " + ((chkDeshabilitar.isSelected()) ? "deshabilitar" : "habilitar"),
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarEspaciosActionPerformed

    public void setUsuario(Usuario u) {
        this.usuario = u;
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        cargarTabla();
    }//GEN-LAST:event_formPropertyChange

    private void chkDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDeshabilitarActionPerformed
        if (chkDeshabilitar.isSelected()) {
            btnEliminarEspacios.setText("Deshabilitar Espacios");
        } else {
            btnEliminarEspacios.setText("Habilitar Espacios");
        }
    }//GEN-LAST:event_chkDeshabilitarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminarEspacios;
    private javax.swing.JCheckBox chkDeshabilitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVisualizarEspacios;
    private javax.swing.JTextField txtBuscarEspacio;
    // End of variables declaration//GEN-END:variables
}
