/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smei.gui.espacios;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import smei.util.Util;

/**
 *
 * @author Ernesto Mancebo T
 */
public class VisualizadorDeEspacios extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizadorDeEspacios
     */
    private static VisualizadorDeEspacios instancia = new VisualizadorDeEspacios();
    private final String[] columnHeaders = {" ", "ID Espacio", "Nombre", "Límite de personas", "Descripción"};
    private final Class[] columnsTypes = {java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class};
    
    private VisualizadorDeEspacios() {
        initComponents();
        initializeValues();
    }
    
    public static VisualizadorDeEspacios getInstance() {
        return instancia;
    }
    
    public void initializeValues() {
        
        tblVisualizarEspacios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblVisualizarEspacios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable target = (JTable) e.getSource();
                    if (target.getSelectedColumn() != 0) {
                        MaestroEspacios activeFrame = MaestroEspacios.getInstance();
                        
                        activeFrame.cargarDataFromID(String.valueOf(target.getValueAt(target.getSelectedRow(), 1)));
                        Util.addFrameToDesktopPanel(getInstance().getDesktopPane(), activeFrame);
                        Util.deshabilitarEdicion(activeFrame);
                        Util.habilitarBtnModificar(activeFrame);
                        Util.habilitarBtnSalir(activeFrame);
                    }
                }
            }
        });

        //Add table Model
        Util.setMultiPuporseModelToTable(tblVisualizarEspacios, new Object[][]{
            {false, 4, null, null, null},
            {false, 56, null, null, null},
            {false, 3, null, null, null},
            {false, 1, null, null, null}
        }, columnHeaders, columnsTypes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarEspacios = new javax.swing.JTable();
        txtBuscarEspacio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarEspacios = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(726, 374));

        tblVisualizarEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisualizarEspacios.setToolTipText("");
        jScrollPane1.setViewportView(tblVisualizarEspacios);

        jLabel1.setText("Buscar:");

        btnEliminarEspacios.setText("Eliminar Espacio");
        btnEliminarEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEspaciosActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarEspacios)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarEspacios)
                    .addComponent(btnAceptar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEspaciosActionPerformed
        ArrayList<String> values = Util.getIDsFromSelectedRows(tblVisualizarEspacios, 0, 1);
        if (!values.isEmpty()) {
            for (String s : values) {
                JOptionPane.showMessageDialog(rootPane, s);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Favor seleccione al menos un espacio para eliminar", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarEspaciosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminarEspacios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVisualizarEspacios;
    private javax.swing.JTextField txtBuscarEspacio;
    // End of variables declaration//GEN-END:variables
}
