/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smei;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ernesto
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        setSize(dimension.width * 9 / 10, dimension.height * 9 / 10);
        setLocation(dimension.width * 1 / 20, dimension.height * 1 / 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTaskPane1 = new com.l2fprod.common.swing.JTaskPane();
        jTaskPaneGroup1 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkButton1 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton2 = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup2 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkButton3 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton4 = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup3 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkButton5 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton6 = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup4 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkButton7 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton8 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton9 = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup5 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkButton10 = new com.l2fprod.common.swing.JLinkButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 581));

        jTaskPane1.setBackground(new java.awt.Color(240, 240, 240));
        jTaskPane1.setMinimumSize(new java.awt.Dimension(201, 380));

        jTaskPaneGroup1.setTitle("Reservas");
        jTaskPaneGroup1.setMaximumSize(new java.awt.Dimension(172, 86));
        jTaskPaneGroup1.setMinimumSize(new java.awt.Dimension(172, 86));

        jLinkButton1.setText("Crear Reserva");

        jLinkButton2.setText("Buscar Reservas");

        javax.swing.GroupLayout jTaskPaneGroup1Layout = new javax.swing.GroupLayout(jTaskPaneGroup1.getContentPane());
        jTaskPaneGroup1.getContentPane().setLayout(jTaskPaneGroup1Layout);
        jTaskPaneGroup1Layout.setHorizontalGroup(
            jTaskPaneGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );
        jTaskPaneGroup1Layout.setVerticalGroup(
            jTaskPaneGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTaskPaneGroup1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLinkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLinkButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTaskPaneGroup2.setTitle("Espacios");

        jLinkButton3.setText("Buscar Espacios");
        jLinkButton3.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton3.setMinimumSize(new java.awt.Dimension(112, 22));

        jLinkButton4.setText("Registrar Espacio");
        jLinkButton4.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton4.setMinimumSize(new java.awt.Dimension(112, 22));

        javax.swing.GroupLayout jTaskPaneGroup2Layout = new javax.swing.GroupLayout(jTaskPaneGroup2.getContentPane());
        jTaskPaneGroup2.getContentPane().setLayout(jTaskPaneGroup2Layout);
        jTaskPaneGroup2Layout.setHorizontalGroup(
            jTaskPaneGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup2Layout.setVerticalGroup(
            jTaskPaneGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup2Layout.createSequentialGroup()
                .addComponent(jLinkButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLinkButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTaskPaneGroup3.setTitle("Historicos");

        jLinkButton5.setText("Tendencias Reservaciones");
        jLinkButton5.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton5.setMinimumSize(new java.awt.Dimension(112, 22));

        jLinkButton6.setText("Consultar Historico Resvaciones");
        jLinkButton6.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton6.setMinimumSize(new java.awt.Dimension(112, 22));

        javax.swing.GroupLayout jTaskPaneGroup3Layout = new javax.swing.GroupLayout(jTaskPaneGroup3.getContentPane());
        jTaskPaneGroup3.getContentPane().setLayout(jTaskPaneGroup3Layout);
        jTaskPaneGroup3Layout.setHorizontalGroup(
            jTaskPaneGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup3Layout.setVerticalGroup(
            jTaskPaneGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLinkButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTaskPaneGroup4.setTitle("Usuario");

        jLinkButton7.setText("Buscar Usuarios");
        jLinkButton7.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton7.setMinimumSize(new java.awt.Dimension(112, 22));

        jLinkButton8.setText("Registrar Usuario");
        jLinkButton8.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton8.setMinimumSize(new java.awt.Dimension(112, 22));

        jLinkButton9.setText("Modificar Contraseña");
        jLinkButton9.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton9.setMinimumSize(new java.awt.Dimension(112, 22));

        javax.swing.GroupLayout jTaskPaneGroup4Layout = new javax.swing.GroupLayout(jTaskPaneGroup4.getContentPane());
        jTaskPaneGroup4.getContentPane().setLayout(jTaskPaneGroup4Layout);
        jTaskPaneGroup4Layout.setHorizontalGroup(
            jTaskPaneGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup4Layout.setVerticalGroup(
            jTaskPaneGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLinkButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLinkButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTaskPaneGroup5.setTitle("Notificaciones");

        jLinkButton10.setText("Modificar Notificaciones");
        jLinkButton10.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkButton10.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTaskPaneGroup5Layout = new javax.swing.GroupLayout(jTaskPaneGroup5.getContentPane());
        jTaskPaneGroup5.getContentPane().setLayout(jTaskPaneGroup5Layout);
        jTaskPaneGroup5Layout.setHorizontalGroup(
            jTaskPaneGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup5Layout.setVerticalGroup(
            jTaskPaneGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jTaskPane1Layout = new javax.swing.GroupLayout(jTaskPane1);
        jTaskPane1.setLayout(jTaskPane1Layout);
        jTaskPane1Layout.setHorizontalGroup(
            jTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTaskPaneGroup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jTaskPane1Layout.createSequentialGroup()
                .addComponent(jTaskPaneGroup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTaskPaneGroup3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTaskPaneGroup4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTaskPaneGroup5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPane1Layout.setVerticalGroup(
            jTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTaskPane1Layout.createSequentialGroup()
                .addComponent(jTaskPaneGroup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTaskPaneGroup2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTaskPaneGroup3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTaskPaneGroup4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTaskPaneGroup5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTaskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLinkButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLinkButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            System.setProperty(
                    "Quaqua.tabLayoutPolicy", "wrap");

            UIManager.setLookAndFeel(
                    ch.randelshofer.quaqua.QuaquaManager.getLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.l2fprod.common.swing.JLinkButton jLinkButton1;
    private com.l2fprod.common.swing.JLinkButton jLinkButton10;
    private com.l2fprod.common.swing.JLinkButton jLinkButton2;
    private com.l2fprod.common.swing.JLinkButton jLinkButton3;
    private com.l2fprod.common.swing.JLinkButton jLinkButton4;
    private com.l2fprod.common.swing.JLinkButton jLinkButton5;
    private com.l2fprod.common.swing.JLinkButton jLinkButton6;
    private com.l2fprod.common.swing.JLinkButton jLinkButton7;
    private com.l2fprod.common.swing.JLinkButton jLinkButton8;
    private com.l2fprod.common.swing.JLinkButton jLinkButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private com.l2fprod.common.swing.JTaskPane jTaskPane1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup2;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup3;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup4;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup5;
    // End of variables declaration//GEN-END:variables
}
