/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smei.gui;

import com.sun.jmx.mbeanserver.ModifiableClassLoaderRepository;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import smei.gui.espacios.MaestroEspacios;
import smei.gui.espacios.VisualizadorDeEspacios;
import smei.gui.reservas.MaestroReservas;
import smei.gui.reservas.VisualizadorDeReservas;
import smei.gui.usuarios.MaestroUsuarios;
import smei.gui.usuarios.ModificarContrasena;
import smei.gui.usuarios.VisualizadorDeUsuarios;
import smei.util.Util;

/**
 *
 * @author Ernesto
 */
public class Principal extends javax.swing.JFrame {

    private JInternalFrame activeFrame = null;
    private static Principal instance = new Principal();

    public static Principal getInstance() {
        return instance;
    }

    /**
     * Creates new form Principal
     */
    private Principal() {
        initComponents();
        initializeValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTaskPane1 = new com.l2fprod.common.swing.JTaskPane();
        jTaskPaneGroup1 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkBtnRegReserva = new com.l2fprod.common.swing.JLinkButton();
        jLinkBtnBuscarReserva = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup2 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkBtnBuscarEspacio = new com.l2fprod.common.swing.JLinkButton();
        jLinkBtnRegEspacio = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup3 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkBtnTendReser = new com.l2fprod.common.swing.JLinkButton();
        jLinkBtnConsHisto = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup4 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkBtnBuscarUsu = new com.l2fprod.common.swing.JLinkButton();
        jLinkBtnRegUsu = new com.l2fprod.common.swing.JLinkButton();
        jLinkBtnModContr = new com.l2fprod.common.swing.JLinkButton();
        jTaskPaneGroup5 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLinkBtnModNotif = new com.l2fprod.common.swing.JLinkButton();
        PrincipalDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTaskPane1.setBackground(new java.awt.Color(240, 240, 240));
        jTaskPane1.setMinimumSize(new java.awt.Dimension(201, 380));

        jTaskPaneGroup1.setTitle("Reservas");
        jTaskPaneGroup1.setMaximumSize(new java.awt.Dimension(172, 86));
        jTaskPaneGroup1.setMinimumSize(new java.awt.Dimension(172, 86));

        jLinkBtnRegReserva.setText("Registro Reserva");
        jLinkBtnRegReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnRegReservaActionPerformed(evt);
            }
        });

        jLinkBtnBuscarReserva.setText("Buscar Reservas");
        jLinkBtnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnBuscarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTaskPaneGroup1Layout = new javax.swing.GroupLayout(jTaskPaneGroup1.getContentPane());
        jTaskPaneGroup1.getContentPane().setLayout(jTaskPaneGroup1Layout);
        jTaskPaneGroup1Layout.setHorizontalGroup(
            jTaskPaneGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkBtnRegReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkBtnBuscarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );
        jTaskPaneGroup1Layout.setVerticalGroup(
            jTaskPaneGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTaskPaneGroup1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLinkBtnRegReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLinkBtnBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTaskPaneGroup2.setTitle("Espacios");

        jLinkBtnBuscarEspacio.setText("Buscar Espacios");
        jLinkBtnBuscarEspacio.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnBuscarEspacio.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkBtnBuscarEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnBuscarEspacioActionPerformed(evt);
            }
        });

        jLinkBtnRegEspacio.setText("Registrar Espacio");
        jLinkBtnRegEspacio.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnRegEspacio.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkBtnRegEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnRegEspacioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTaskPaneGroup2Layout = new javax.swing.GroupLayout(jTaskPaneGroup2.getContentPane());
        jTaskPaneGroup2.getContentPane().setLayout(jTaskPaneGroup2Layout);
        jTaskPaneGroup2Layout.setHorizontalGroup(
            jTaskPaneGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkBtnBuscarEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkBtnRegEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup2Layout.setVerticalGroup(
            jTaskPaneGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup2Layout.createSequentialGroup()
                .addComponent(jLinkBtnRegEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLinkBtnBuscarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTaskPaneGroup3.setTitle("Historicos");

        jLinkBtnTendReser.setText("Tendencias Reservaciones");
        jLinkBtnTendReser.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnTendReser.setMinimumSize(new java.awt.Dimension(112, 22));

        jLinkBtnConsHisto.setText("Consultar Historico Resvaciones");
        jLinkBtnConsHisto.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnConsHisto.setMinimumSize(new java.awt.Dimension(112, 22));

        javax.swing.GroupLayout jTaskPaneGroup3Layout = new javax.swing.GroupLayout(jTaskPaneGroup3.getContentPane());
        jTaskPaneGroup3.getContentPane().setLayout(jTaskPaneGroup3Layout);
        jTaskPaneGroup3Layout.setHorizontalGroup(
            jTaskPaneGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkBtnTendReser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkBtnConsHisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup3Layout.setVerticalGroup(
            jTaskPaneGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLinkBtnConsHisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkBtnTendReser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTaskPaneGroup4.setTitle("Usuario");

        jLinkBtnBuscarUsu.setText("Buscar Usuarios");
        jLinkBtnBuscarUsu.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnBuscarUsu.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkBtnBuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnBuscarUsuActionPerformed(evt);
            }
        });

        jLinkBtnRegUsu.setText("Registrar Usuario");
        jLinkBtnRegUsu.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnRegUsu.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkBtnRegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnRegUsuActionPerformed(evt);
            }
        });

        jLinkBtnModContr.setText("Modificar Contraseña");
        jLinkBtnModContr.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnModContr.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkBtnModContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnModContrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTaskPaneGroup4Layout = new javax.swing.GroupLayout(jTaskPaneGroup4.getContentPane());
        jTaskPaneGroup4.getContentPane().setLayout(jTaskPaneGroup4Layout);
        jTaskPaneGroup4Layout.setHorizontalGroup(
            jTaskPaneGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkBtnBuscarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkBtnRegUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinkBtnModContr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup4Layout.setVerticalGroup(
            jTaskPaneGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLinkBtnRegUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkBtnBuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLinkBtnModContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTaskPaneGroup5.setTitle("Notificaciones");

        jLinkBtnModNotif.setText("Modificar Notificaciones");
        jLinkBtnModNotif.setMaximumSize(new java.awt.Dimension(112, 22));
        jLinkBtnModNotif.setMinimumSize(new java.awt.Dimension(112, 22));
        jLinkBtnModNotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkBtnModNotifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTaskPaneGroup5Layout = new javax.swing.GroupLayout(jTaskPaneGroup5.getContentPane());
        jTaskPaneGroup5.getContentPane().setLayout(jTaskPaneGroup5Layout);
        jTaskPaneGroup5Layout.setHorizontalGroup(
            jTaskPaneGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinkBtnModNotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPaneGroup5Layout.setVerticalGroup(
            jTaskPaneGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTaskPaneGroup5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkBtnModNotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jTaskPane1Layout = new javax.swing.GroupLayout(jTaskPane1);
        jTaskPane1.setLayout(jTaskPane1Layout);
        jTaskPane1Layout.setHorizontalGroup(
            jTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTaskPaneGroup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jTaskPane1Layout.createSequentialGroup()
                .addComponent(jTaskPaneGroup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTaskPaneGroup3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTaskPaneGroup4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTaskPaneGroup5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTaskPane1Layout.setVerticalGroup(
            jTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTaskPane1Layout.createSequentialGroup()
                .addComponent(jTaskPaneGroup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTaskPaneGroup2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTaskPaneGroup3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jTaskPaneGroup4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTaskPaneGroup5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PrincipalDesktopPane.setBackground(getBackground());

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrincipalDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrincipalDesktopPane)
                    .addComponent(jTaskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getPrincipalDesktopPane() {
        return PrincipalDesktopPane;
    }

    private void initializeValues() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(dimension.width * 9 / 10, dimension.height * 9 / 10);
        setLocation(dimension.width * 1 / 20, dimension.height * 1 / 20);
//        getInstance().setIconImage(new ImageIcon(getClass().getResource("/resources/icons/schedule-48.png")));
    }
    private void jLinkBtnModNotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnModNotifActionPerformed
    }//GEN-LAST:event_jLinkBtnModNotifActionPerformed

    private void jLinkBtnRegReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnRegReservaActionPerformed
        activeFrame = MaestroReservas.getInstance();
        agregarMaestroInternalFrame("Registrar Reservacion");
    }//GEN-LAST:event_jLinkBtnRegReservaActionPerformed

    private void jLinkBtnRegEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnRegEspacioActionPerformed
        activeFrame = MaestroEspacios.getInstance();
        agregarMaestroInternalFrame("Registrar Espacio");
    }//GEN-LAST:event_jLinkBtnRegEspacioActionPerformed

    private void jLinkBtnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnBuscarReservaActionPerformed
        activeFrame = VisualizadorDeReservas.getInstance();
        agregarVisualizadorInternalFrame("Buscar Reserva");

    }//GEN-LAST:event_jLinkBtnBuscarReservaActionPerformed

    private void jLinkBtnBuscarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnBuscarEspacioActionPerformed
        activeFrame = VisualizadorDeEspacios.getInstance();
        agregarVisualizadorInternalFrame("Buscar Espacio");
    }//GEN-LAST:event_jLinkBtnBuscarEspacioActionPerformed

    private void jLinkBtnRegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnRegUsuActionPerformed
        activeFrame = MaestroUsuarios.getInstance();
        agregarVisualizadorInternalFrame("Registrar Usuario");
    }//GEN-LAST:event_jLinkBtnRegUsuActionPerformed

    private void jLinkBtnBuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnBuscarUsuActionPerformed
        activeFrame = VisualizadorDeUsuarios.getInstance();
        agregarMaestroInternalFrame("Buscar Usuario");
    }//GEN-LAST:event_jLinkBtnBuscarUsuActionPerformed

    private void jLinkBtnModContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkBtnModContrActionPerformed
        activeFrame = ModificarContrasena.getInstance();
        agregarMaestroInternalFrame("Modificar Contraseña");
    }//GEN-LAST:event_jLinkBtnModContrActionPerformed

    private void agregarMaestroInternalFrame(String titulo) {
        Util.addFrameToDesktopPanel(PrincipalDesktopPane, activeFrame);
        Util.asignarTitulo(activeFrame, titulo);
        Util.habilitarEdicion(activeFrame);
        Util.deshabilitarBtnModificar(activeFrame);
    }

    private void agregarVisualizadorInternalFrame(String titulo) {
        Util.addFrameToDesktopPanel(PrincipalDesktopPane, activeFrame);
        Util.asignarTitulo(activeFrame, titulo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            System.out.println(e.toString());
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PrincipalDesktopPane;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnBuscarEspacio;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnBuscarReserva;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnBuscarUsu;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnConsHisto;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnModContr;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnModNotif;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnRegEspacio;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnRegReserva;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnRegUsu;
    private com.l2fprod.common.swing.JLinkButton jLinkBtnTendReser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private com.l2fprod.common.swing.JTaskPane jTaskPane1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup2;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup3;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup4;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup5;
    // End of variables declaration//GEN-END:variables
}
